name: form_controller
description: A controller to combine multible TextControllers and managing form satate.

version: 0.5.0
homepage: https://github.com/micazi/form_controller

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
