name: form_controller
description: A controller to combine multible TextControllers and managing form satate.

version: 0.8.4
homepage: https://github.com/micazi/form_controller

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
